# Generated by Django 4.1.7 on 2023-03-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_create'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Create',
        ),
    ]
